In [2]:
import pandas as pd
import numpy as np

In [4]:
populacao = pd.read_excel("Planilhas/total_populacao_sergipe.xls")
print populacao.shape
populacao.head()

(77, 8)

,Código do município,Nome do município,Total da população 2000,Total de homens,Total de mulheres,Total da população urbana,Total da população rural,Total da população 2010
0,2800100,Amparo de São Francisco,2182,1135,1140,1840,435,2275
1,2800209,Aquidabã,18344,9808,10258,11460,8606,20066
2,2800308,Aracaju,461534,265321,305616,570937,0,570937
3,2800407,Arauá,9762,4887,4812,4486,5213,9699
4,2800506,Areia Branca,14824,8511,8371,8191,8691,16882

In [6]:
equipamentos = pd.read_excel("Planilhas/Equipamentos por município.xls")

In [99]:
ans = pd.read_excel("ANS Vidas Assistidas NE.xls")
ans.head()

                      Município  Assistência_Médica
0             210005 Açailândia               11827
1           210010 Afonso Cunha                  12
2  210015 Água Doce do Maranhão                  12
3              210020 Alcântara                 463
4          210030 Aldeias Altas                 420

In [100]:
pib = pd.read_excel("PIBMunicipal2008-2012.xlsx", header=5, parse_cols="A,F,G")
# Ajustar o slide para o Estado sendo processado
pib = pib[1769:1844]
pib

                     Município         2012  Per capita (R$) 2012
1769   Amparo de São Francisco    18469.054               8065.09
1770                  Aquidabã   142671.105               7022.94
1771                   Aracaju  9813851.609              16698.72
1772                     Arauá    70589.138               7434.35
1773              Areia Branca   130047.550               7576.76
1774       Barra dos Coqueiros   333515.485              12798.48
1775                    Boquim   294652.052              11453.03
1776              Brejo Grande    57110.660               7285.45
1777            Campo do Brito   116939.272               6884.04
1778                   Canhoba    30208.789               7638.13
1779  Canindé de São Francisco  1399830.529              54398.26
1780                    Capela   267146.001               8507.29
1781                    Carira   147503.367               7250.10
1782                Carmópolis   620406.715              43907.06
1783         Cedro de São João    35242.691               6213.45
1784             Cristinápolis   109120.486               6472.54
1785                     Cumbe    29635.909               7719.69
1786            Divina Pastora   211624.004              47163.81
1787                  Estância  1303712.678              19987.62
1788                Feira Nova    42331.158               7893.19
1789                Frei Paulo   194721.792              13749.60
1790                    Gararu    80742.712               7075.25
1791           General Maynard    19125.183               6355.99
1792            Gracho Cardoso    41017.621               7240.53
1793           Ilha das Flores    47602.808               5694.80
1794                 Indiaroba    99512.977               6129.16
1795                 Itabaiana  1005866.162              11365.59
1796              Itabaianinha   250449.941               6351.44
1797                     Itabi    38640.205               7818.74
1798        Itaporanga d'Ajuda   600482.748              19267.86
...                        ...          ...                   ...
1814  Nossa Senhora de Lourdes    42042.523               6704.28
1815  Nossa Senhora do Socorro  2049719.308              12407.95
1816                  Pacatuba   111861.631               8360.99
1817                Pedra Mole    21850.498               7220.92
1818                 Pedrinhas    50293.335               5606.84
1819                    Pinhão    41139.348               6761.89
1820                   Pirambu    69584.609               8149.99
1821              Poço Redondo   187705.974               5937.43
1822                Poço Verde   133678.448               5998.05
1823            Porto da Folha   197471.551               7214.89
1824                   Propriá   313990.016              10974.07
1825         Riachão do Dantas   113901.537               5866.98
1826                 Riachuelo   148608.454              15628.19
1827              Ribeirópolis   152027.072               8719.65
1828         Rosário do Catete   408965.323              42863.99
1829                   Salgado   118824.982               6112.71
1830     Santa Luzia do Itanhy   101227.623               7188.95
1831        Santa Rosa de Lima    26201.708               6944.53
1832  Santana do São Francisco    41939.351               5845.21
1833    Santo Amaro das Brotas   107527.486               9332.36
1834             São Cristóvão   590068.921               7283.81
1835              São Domingos    66069.671               6338.23
1836             São Francisco    23585.720               6692.88
1837      São Miguel do Aleixo    27030.731               7235.21
1838                Simão Dias   374946.437               9616.97
1839                    Siriri   162853.112              19935.50
1840                     Telha    21369.704               7109.02
1841            Tobias Barreto   337076.507               6910.70
1842             Tomar do Geru    77866.561               6055.88
1843                   Umbaúba   167750.043               7223.44

[75 rows x 3 columns]

In [101]:
columns = [u"Município", u"Produto Interno Bruto (R$ 1.000 )", u"PIB per capita (R$)", u"Quantidade (Pessoas)", "Vidas Assistidas ANS"]
result_final = pd.DataFrame(columns=columns)

city_list=[]
for row in populacao.iterrows():
    try:
        city_code = int(row[1][u"Código do município"][:-1])
        city_pop = int(row[1][u"Total da população 2010"])
        city_name = row[1][u"Nome do município"]
        
        result2 = ans[ans[u"Município"].map(lambda x: str(city_code) in x)]
        
        if result2.empty:
            city_assist = 0
        else:        
            city_assist = int(result2[u"Assistência_Médica"])
        
        result3 = pib[pib[u"Município"]==city_name]
        
        if result3.empty:
            city_pib = 0
            city_pib_per_capita = 0
            
        else:
            city_pib = float(result3[2012])        
            city_pib_per_capita = float(result3[u"Per capita (R$) 2012"])
        
        city_list.append({u"Município":city_name, u"Produto Interno Bruto (R$ 1.000 )":city_pib, u"PIB per capita (R$)":city_pib_per_capita, u"Quantidade (Pessoas)":city_pop, "Vidas Assistidas ANS":city_assist})
    except ValueError:
        print 'ValueError'
        continue
    except TypeError:
        print 'TypeError'
        print result3.head()
        print city_name
        continue

result_final = result_final.append(city_list, ignore_index=True)

# Trocar o nome da planilha para o Estado sendo processado
result_final.to_excel("Cobertura SE.xls")

ValueError
ValueError

In [103]:
curr_city = int(populacao[u"Código do município"][10][:-1])
curr_city_population = populacao[u"Total da população 2010"][10]
curr_city_name = populacao[u"Nome do município"][10]
equip = equipamentos[equipamentos["cidade"]==curr_city]

raio_x = equip[equip["equipamento"].map(lambda x: "raio x" in x.encode('utf8').lower() )]
ultrassom = equip[equip["equipamento"].map(lambda x: "ultrassom" in x.encode('utf8').lower() )]
ressonancia = equip[equip["equipamento"].map(lambda x: "ressonancia" in x.encode('utf8').lower() )]
tomografo = equip[equip["equipamento"].map(lambda x: "tomógrafo" in x.encode('utf8').lower() )]
pet_ct = equip[equip["equipamento"].map(lambda x: "pet/ct" in x.encode('utf8').lower() )]

total_sum = {}
total_sum.update({"XP": raio_x["existentes"].sum()})
total_sum.update({"US": ultrassom["existentes"].sum()})
total_sum.update({"MR": ressonancia["existentes"].sum()})
total_sum.update({"CT": tomografo["existentes"].sum()})
total_sum.update({"MI": pet_ct["existentes"].sum()})

print total_sum

sum_xp = raio_x[["existentes"]].sum()
sum_us = ultrassom[["existentes"]].sum().append(sum_xp)
sum_mr = ressonancia[["existentes"]].sum().append(sum_us)
sum_ct = tomografo[["existentes"]].sum().append(sum_mr)
sum_mi = pet_ct[["existentes"]].sum().append(sum_ct)

# df_sum = pd.DataFrame(data=sum_mi, columns=["XP", "US", "MR", "CT", "MI"])
# df_sum = df_sum.append(sum_us, ignore_index=True)
# pd.merge(df_sum, sum_ultrassom)
# df_sum = df_sum.append(sum_ultrassom, ignore_index=True)
# df_sum
sum_mi

{'XP': 4, 'CT': 0, 'MI': 0, 'US': 2, 'MR': 0}

existentes    0
existentes    0
existentes    0
existentes    2
existentes    4
dtype: float64

In [120]:
result3 = pib[pib[u"Município"]==curr_city_name]
result3

                Município       2012  Per capita (R$) 2012
470  Amarante do Maranhão  177657.88               4560.83

In [129]:
city_pib = float(result3[2012])
city_pib_per_capita = float(result3[u"Per capita (R$) 2012"])
city_assist = int(result2[u"Assistência_Médica"])
city_pib, city_assist

(177657.88, 246)

In [139]:
dict_result = {u"Município":curr_city_name, u"Produto Interno Bruto (R$ 1.000 )":city_pib, u"PIB per capita (R$)": city_pib_per_capita, u"Quantidade (Pessoas)":curr_city_population, "Vidas Assistidas ANS":city_assist}
columns = dict_result.keys()
result_final = pd.DataFrame(data=dict_result, index=["Município"])
pd.pivot_table(result_final, index=[u"Município"])

,PIB per capita (R$),Produto Interno Bruto (R$ 1.000 ),Quantidade (Pessoas),Vidas Assistidas ANS
Município,,,,
Amarante do Maranhão,4560.83,177657.88,37894,246