In [1]:
import pandas as pd
import numpy as np

In [2]:
ans = pd.read_excel("Planilhas/ANS Vidas Assistidas.xls", sheetname="Sudeste")
ans.head()

                    Município  Assistência Médica
0  310010 Abadia dos Dourados                1173
1               310020 Abaeté                3297
2           310030 Abre Campo                4900
3              310040 Acaiaca                 232
4              310050 Açucena                1174

In [4]:
equipamentos = pd.read_excel("Planilhas/Equipamentos por município Sudeste.xls")

In [5]:
def get_equipment(equip):
    raio_x = equip[equip["equipamento"].map(lambda x: "raio x" in x.encode('utf8').lower() and "dentario" not in x.encode('utf8').lower() and "densitometria" not in x.encode('utf8').lower() )]
    mamografo = equip[equip["equipamento"].map(lambda x: "mamografo" in x.encode('utf8').lower() )]
    ultrassom = equip[equip["equipamento"].map(lambda x: "ultrassom" in x.encode('utf8').lower() )]
    ressonancia = equip[equip["equipamento"].map(lambda x: "ressonancia" in x.encode('utf8').lower() )]
    tomografo = equip[equip["equipamento"].map(lambda x: "tomógrafo" in x.encode('utf8').lower() )]
    pet_ct = equip[equip["equipamento"].map(lambda x: "pet/ct" in x.encode('utf8').lower() )]
    gama = equip[equip["equipamento"].map(lambda x: "gama" in x.encode('utf8').lower() )]
    
    total_sum = {"XP":0, "US": 0, "MR":0, "CT":0, "MI":0}
    
    if not raio_x.empty:
        total_sum.update({"XP": raio_x["existentes"].sum() + mamografo["existentes"].sum()})
    if not ultrassom.empty:
        total_sum.update({"US": ultrassom["existentes"].sum()})
    if not ressonancia.empty:
        total_sum.update({"MR": ressonancia["existentes"].sum()})
    if not tomografo.empty:
        total_sum.update({"CT": tomografo["existentes"].sum()})
    if not pet_ct.empty:
        total_sum.update({"MI": pet_ct["existentes"].sum() + gama["existentes"].sum()})
    
    return total_sum

In [16]:
populacao = pd.read_excel("Planilhas/Sudeste/total_populacao_sao_paulo.xls")
print(populacao.shape)
populacao.head()

(647, 8)

,Código do município,Nome do município,Total da população 2000,Total de homens,Total de mulheres,Total da população urbana,Total da população rural,Total da população 2010
0,3500105,Adamantina,33497,16375,17422,31948,1849,33797
1,3500204,Adolfo,3684,1787,1770,3200,357,3557
2,3500303,Aguaí,28195,16224,15944,29021,3147,32168
3,3500402,Águas da Prata,7131,3742,3838,6766,814,7580
4,3500501,Águas de Lindóia,16190,8453,8808,17108,153,17261

In [17]:
pib = pd.read_excel("Planilhas/PIBMunicipal2008-2012.xlsx", header=5, parse_cols="A,F,G")
# Ajustar o slide para o Estado sendo processado
pib = pib[3290:3935]
pib

                   Município         2012  Per capita (R$) 2012
3290              Adamantina   641663.616              18960.01
3291                  Adolfo    86984.233              24585.71
3292                   Aguaí   601304.466              18363.25
3293          Águas da Prata   119340.238              15593.92
3294        Águas de Lindóia   238651.287              13685.70
3295  Águas de Santa Bárbara   138284.782              24440.58
3296      Águas de São Pedro    67498.411              23834.18
3297                  Agudos  1165486.218              33459.25
3298                Alambari    87588.127              17272.36
3299       Alfredo Marcondes    58998.253              15046.74
3300                  Altair   164711.173              42682.35
3301             Altinópolis   363820.103              23281.51
3302             Alto Alegre    79152.014              19409.52
3303                Alumínio  1526433.160              89374.86
3304        Álvares Florence    88446.491              23068.99
3305         Álvares Machado   269694.287              11407.42
3306      Álvaro de Carvalho    47596.668              10058.47
3307             Alvinlândia    38694.329              12791.51
3308               Americana  7131531.813              33189.52
3309     Américo Brasiliense   557896.469              15754.00
3310       Américo de Campos    74380.997              12996.85
3311                  Amparo  2332510.688              34996.93
3312               Analândia    90132.526              20480.01
3313               Andradina  1322018.205              23879.96
3314                Angatuba   569168.957              25128.87
3315                 Anhembi   146019.138              25080.58
3316                 Anhumas    55010.303              14522.26
3317               Aparecida   528522.664              15090.73
3318       Aparecida d'Oeste    55863.323              12762.93
3319                   Apiaí   368619.019              14807.54
...                      ...          ...                   ...
3905                Tremembé   530196.373              12649.32
3906         Três Fronteiras    71032.083              12990.51
3907                  Tuiuti    75835.265              12477.01
3908                    Tupã  1337760.453              21067.76
3909           Tupi Paulista   224594.663              15577.38
3910                 Turiúba    47588.947              24581.07
3911               Turmalina    38852.013              20235.42
3912                 Ubarana   107694.274              19756.79
3913                 Ubatuba  1075555.283              13343.70
3914               Ubirajara    65467.184              14652.46
3915                   Uchoa   171844.156              18018.68
3916          União Paulista    47389.487              28966.68
3917                  Urânia   122893.195              13905.09
3918                     Uru    32199.540              26221.12
3919                  Urupês   221768.163              17260.91
3920         Valentim Gentil   229468.598              20121.76
3921                Valinhos  4123322.448              37352.32
3922              Valparaíso   404938.074              17468.53
3923                  Vargem    81386.247               8966.21
3924    Vargem Grande do Sul   601435.363              15144.16
3925  Vargem Grande Paulista  1033300.623              23191.57
3926         Várzea Paulista  1759719.602              16107.72
3927               Vera Cruz   124943.362              11652.99
3928                 Vinhedo  6561500.721              99285.80
3929               Viradouro   221680.887              12668.20
3930    Vista Alegre do Alto   183244.413              25422.37
3931          Vitória Brasil    26529.157              15185.55
3932              Votorantim  2067784.873              18669.90
3933             Votuporanga  1590507.956              18481.60
3934                Zacarias    58083.623              24262.16

[645 rows x 3 columns]

In [18]:
columns = [u"Município", u"Produto Interno Bruto (R$ 1.000 )", u"PIB per capita (R$)", u"Quantidade (Pessoas)", "Vidas Assistidas ANS", "XP", "US", "MR", "CT", "MI"]
result_final = pd.DataFrame(columns=columns)

city_list=[]
for row in populacao.iterrows():
    try:
        city_code = int(row[1][u"Código do município"][:-1])
        city_pop = int(row[1][u"Total da população 2010"])
        city_name = row[1][u"Nome do município"]
        
        # Obtém a quantidade de vidas assistidas
        result2 = ans[ans[u"Município"].map(lambda x: str(city_code) in x)]
        
        if result2.empty:
            city_assist = 0
        else:        
            city_assist = int(result2[u"Assistência Médica"])
        
        # Obtém PIB e PIB per capita
        result3 = pib[pib[u"Município"]==city_name]
        
        if result3.empty:
            city_pib = 0
            city_pib_per_capita = 0 
        else:
            city_pib = float(result3[2012])        
            city_pib_per_capita = float(result3[u"Per capita (R$) 2012"])
            
        info_dict = {u"Município":city_name, u"Produto Interno Bruto (R$ 1.000 )":city_pib, u"PIB per capita (R$)":city_pib_per_capita, u"Quantidade (Pessoas)":city_pop, "Vidas Assistidas ANS":city_assist}
            
        # Obtém a quantidade de máquinas por categoria
        equip = equipamentos[equipamentos["cidade"]==city_code]
        total_sum = get_equipment(equip)
        
        info_dict.update(total_sum)
        city_list.append(info_dict)

    except ValueError:
        print 'ValueError'
        continue
    except TypeError:
        print 'TypeError'
        print result3.head()
        print city_name
        continue

result_final = result_final.append(city_list, ignore_index=True)

# Trocar o nome da planilha para o Estado sendo processado
result_final.to_excel("Cobertura SP.xls")

ValueError
ValueError

In [103]:
curr_city = int(populacao[u"Código do município"][10][:-1])
curr_city_population = populacao[u"Total da população 2010"][10]
curr_city_name = populacao[u"Nome do município"][10]
equip = equipamentos[equipamentos["cidade"]==curr_city]

raio_x = equip[equip["equipamento"].map(lambda x: "raio x" in x.encode('utf8').lower() )]
ultrassom = equip[equip["equipamento"].map(lambda x: "ultrassom" in x.encode('utf8').lower() )]
ressonancia = equip[equip["equipamento"].map(lambda x: "ressonancia" in x.encode('utf8').lower() )]
tomografo = equip[equip["equipamento"].map(lambda x: "tomógrafo" in x.encode('utf8').lower() )]
pet_ct = equip[equip["equipamento"].map(lambda x: "pet/ct" in x.encode('utf8').lower() )]

total_sum = {}
total_sum.update({"XP": raio_x["existentes"].sum()})
total_sum.update({"US": ultrassom["existentes"].sum()})
total_sum.update({"MR": ressonancia["existentes"].sum()})
total_sum.update({"CT": tomografo["existentes"].sum()})
total_sum.update({"MI": pet_ct["existentes"].sum()})

print total_sum

sum_xp = raio_x[["existentes"]].sum()
sum_us = ultrassom[["existentes"]].sum().append(sum_xp)
sum_mr = ressonancia[["existentes"]].sum().append(sum_us)
sum_ct = tomografo[["existentes"]].sum().append(sum_mr)
sum_mi = pet_ct[["existentes"]].sum().append(sum_ct)

# df_sum = pd.DataFrame(data=sum_mi, columns=["XP", "US", "MR", "CT", "MI"])
# df_sum = df_sum.append(sum_us, ignore_index=True)
# pd.merge(df_sum, sum_ultrassom)
# df_sum = df_sum.append(sum_ultrassom, ignore_index=True)
# df_sum
# sum_mi

{'XP': 4, 'CT': 0, 'MI': 0, 'US': 2, 'MR': 0}

existentes    0
existentes    0
existentes    0
existentes    2
existentes    4
dtype: float64

In [120]:
result3 = pib[pib[u"Município"]==curr_city_name]
result3

                Município       2012  Per capita (R$) 2012
470  Amarante do Maranhão  177657.88               4560.83

In [129]:
city_pib = float(result3[2012])
city_pib_per_capita = float(result3[u"Per capita (R$) 2012"])
city_assist = int(result2[u"Assistência_Médica"])
city_pib, city_assist

(177657.88, 246)

In [139]:
dict_result = {u"Município":curr_city_name, u"Produto Interno Bruto (R$ 1.000 )":city_pib, u"PIB per capita (R$)": city_pib_per_capita, u"Quantidade (Pessoas)":curr_city_population, "Vidas Assistidas ANS":city_assist}
columns = dict_result.keys()
result_final = pd.DataFrame(data=dict_result, index=["Município"])
pd.pivot_table(result_final, index=[u"Município"])

,PIB per capita (R$),Produto Interno Bruto (R$ 1.000 ),Quantidade (Pessoas),Vidas Assistidas ANS
Município,,,,
Amarante do Maranhão,4560.83,177657.88,37894,246